apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - configmap-backend.yaml
  - secret-backend.yaml
  - secret-mysql.yaml
  - pvc-mysql.yaml
  - deployment-mysql.yaml
  - service-mysql.yaml
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress-app.yaml
configMapGenerator:
  - name: hbm-rag-mysql-init
    files:
      - hbm_erd_ddl.sql=./hbm_erd_ddl.sql
