apiVersion: v1
kind: Service
metadata:
  name: hbm-rag-frontend
  namespace: class-2
spec:
  selector:
    app: hbm-rag-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

# 프론트 Pod를 frontend라는 고정 서비스명으로 노출
# ingress가 해당 서비스로 들어옴
