apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk057-frontend
  namespace: class-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk057-frontend
  template:
    metadata:
      labels:
        app: sk057-frontend
    spec:
      containers:
        - name: frontend
          image: amdp-registry.skala-ai.com/skala26a-ai2/sk057-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

# nginx 기반 프론트를 Pod로 띄움
